apiVersion: maistra.io/v1
kind: ServiceMeshExtension
metadata:
  name: ossm-example-body-extension
spec:
  config: secret
  image: quay.io/isanchez/ossm-example-body-extension:1.0.0
  phase: PostAuthZ
  priority: 100
  workloadSelector:
    labels:
      app: httpbin